export let tasks = [
    { id: 1, label: "Work", title: "Complete project report", description: "Finish the final report and submit it before the deadline.", dueDate: "25/02/2025", status: 1, archive: 0 },
    { id: 2, label: "Personal", title: "Buy groceries", description: "Milk, eggs, bread, and vegetables.", dueDate: "26/02/2025", status: 1, archive: 1 },
    { id: 3, label: "Others", title: "Car maintenance", description: "Take the car for a routine check-up.", dueDate: "28/02/2025", status: 0, archive: 0 },
    { id: 4, label: "Work", title: "Prepare for team meeting", description: "Gather all necessary reports and presentations.", dueDate: "01/03/2025", status: 0, archive: 1 },
    { id: 5, label: "Personal", title: "Go to the gym", description: "Attend yoga and cardio session.", dueDate: "02/03/2025", status: 1, archive: 0 },
    { id: 6, label: "Others", title: "Read a book", description: "Finish reading 'Atomic Habits'.", dueDate: "03/03/2025", status: 0, archive: 1 },
    { id: 7, label: "Work", title: "Update project timeline", description: "Adjust deadlines based on progress.", dueDate: "04/03/2025", status: 1, archive: 1 },
    { id: 8, label: "Personal", title: "Call mom", description: "Check in and have a chat.", dueDate: "05/03/2025", status: 0, archive: 0 },
    { id: 9, label: "Others", title: "Fix leaking faucet", description: "Buy new washers and replace them.", dueDate: "06/03/2025", status: 0, archive: 1 },
    { id: 10, label: "Work", title: "Review budget report", description: "Analyze Q1 expenses and adjust.", dueDate: "07/03/2025", status: 1, archive: 0 },
    { id: 11, label: "Personal", title: "Plan weekend trip", description: "Decide on destination and book tickets.", dueDate: "08/03/2025", status: 1, archive: 1 },
    { id: 12, label: "Others", title: "Organize closet", description: "Sort clothes and donate unused items.", dueDate: "09/03/2025", status: 0, archive: 1 },
    { id: 13, label: "Work", title: "Client meeting", description: "Discuss project progress and next steps.", dueDate: "10/03/2025", status: 0, archive: 0 },
    { id: 14, label: "Personal", title: "Cook dinner", description: "Try a new recipe for pasta.", dueDate: "11/03/2025", status: 1, archive: 0 },
    { id: 15, label: "Others", title: "Wash car", description: "Clean interior and exterior.", dueDate: "12/03/2025", status: 0, archive: 1 },
    { id: 16, label: "Work", title: "Research new tools", description: "Find productivity software for the team.", dueDate: "13/03/2025", status: 1, archive: 0 },
    { id: 17, label: "Personal", title: "Practice guitar", description: "Learn a new song.", dueDate: "14/03/2025", status: 0, archive: 1 },
    { id: 18, label: "Others", title: "Backup files", description: "Save important documents to cloud storage.", dueDate: "15/03/2025", status: 1, archive: 0 },
    { id: 19, label: "Work", title: "Submit expense report", description: "Ensure all receipts are attached.", dueDate: "16/03/2025", status: 0, archive: 1 },
    { id: 20, label: "Personal", title: "Meditate", description: "Practice mindfulness for 15 minutes.", dueDate: "17/03/2025", status: 1, archive: 1 },
    { id: 21, label: "Others", title: "Clean garage", description: "Throw away old items and reorganize.", dueDate: "18/03/2025", status: 0, archive: 0 },
    { id: 22, label: "Work", title: "Write blog post", description: "Topic: Best remote work practices.", dueDate: "19/03/2025", status: 1, archive: 1 },
    { id: 23, label: "Personal", title: "Watch a movie", description: "Check out a new release.", dueDate: "20/03/2025", status: 0, archive: 0 },
    { id: 24, label: "Others", title: "Paint the fence", description: "Buy paint and brushes.", dueDate: "21/03/2025", status: 1, archive: 0 },
    { id: 25, label: "Work", title: "Team brainstorming", description: "Generate new ideas for Q2.", dueDate: "22/03/2025", status: 0, archive: 1 },
    { id: 26, label: "Personal", title: "Journal entry", description: "Write about the day's experiences.", dueDate: "23/03/2025", status: 1, archive: 0 },
    { id: 27, label: "Others", title: "Check smoke detectors", description: "Replace batteries if needed.", dueDate: "24/03/2025", status: 0, archive: 1 },
    { id: 28, label: "Work", title: "Finish coding module", description: "Push changes to repository.", dueDate: "25/03/2025", status: 1, archive: 0 },
    { id: 29, label: "Personal", title: "Go for a walk", description: "Relax in the park.", dueDate: "26/03/2025", status: 0, archive: 0 },
    { id: 30, label: "Others", title: "Plant new flowers", description: "Spring garden setup.", dueDate: "27/03/2025", status: 1, archive: 1 }
];
